
import java.net.URL;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @authors Derouich Elyes && ElMay Zied && Najar Atef
 */
public class Resultat1 extends javax.swing.JFrame {

    /**
     * Creates new form Resultat
     */
    int score;
    
    public Resultat1 (int score, ArrayList but) {
        this.score=score;
        initComponents();
        jLabel3.setText("Votre score : "+score);
        URL lien = getClass().getResource("images/" + but.get(0) + "_Small.png");
        coul1.setIcon(new ImageIcon(lien));
        lien = getClass().getResource("images/" + but.get(1) + "_Small.png");
        coul2.setIcon(new ImageIcon(lien));
        lien = getClass().getResource("images/" + but.get(2) + "_Small.png");
        coul3.setIcon(new ImageIcon(lien));
        lien = getClass().getResource("images/" + but.get(3) + "_Small.png");
        coul4.setIcon(new ImageIcon(lien));
    }
    
    public Resultat1 () {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        coul4 = new javax.swing.JLabel();
        coul3 = new javax.swing.JLabel();
        coul2 = new javax.swing.JLabel();
        coul1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Open Sans Semibold", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Votre score : ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 220, 300, 18);

        jLabel4.setFont(new java.awt.Font("Open Sans Semibold", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Combainison : ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 160, 100, 18);
        getContentPane().add(coul4);
        coul4.setBounds(310, 160, 30, 20);
        getContentPane().add(coul3);
        coul3.setBounds(260, 160, 30, 20);
        getContentPane().add(coul2);
        coul2.setBounds(210, 160, 30, 20);
        getContentPane().add(coul1);
        coul1.setBounds(160, 160, 30, 20);

        jLabel2.setFont(new java.awt.Font("Open Sans Semibold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("  V o u s   A v e z   P e r d u   ! ");
        jLabel2.setMaximumSize(new java.awt.Dimension(400, 300));
        jLabel2.setMinimumSize(new java.awt.Dimension(400, 300));
        jLabel2.setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -10, 390, 270);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resultat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resultat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resultat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resultat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resultat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel coul1;
    private javax.swing.JLabel coul2;
    private javax.swing.JLabel coul3;
    private javax.swing.JLabel coul4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
